pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                dir ('C:/opt/apache-maven-3.8.4/bin'){
                bat 'mvn package'
                }
            }
        }
        stage('Test') {
            steps {
                // dir("<Your path where scripts are present>")
                dir ("C:/HelloWorld"){
                // Execute your java file
                bat 'dir'
                }
            }
        }
        stage('Deliver') {
            steps {
                bat 'mvn'
            }
        }
    }
}
