pipeline {
    agent any
    
    stages {
        stage ('Build') {
            git url: 'https://github.com/dremaux/projetGOsecurie'
            withMaven {
              bat "mvn"
            } // withMaven will discover the generated Maven artifacts, JUnit Surefire & FailSafe reports and FindBugs reports
          }
        stage('Test') {
            steps {
                // dir("<Your path where scripts are present>")
                dir ("C:/HelloWorld"){
                // Execute your java file
                bat 'dir'
                }
            }
        }
        stage('Deliver') {
            steps {
                bat 'mvn'
            }
        }
    }
}
